#ifndef DEBUG_LIGHT_H
#define DEBUG_LIGHT_H

/* LED */
#define LED_DRAG_LEFT_SET             HAL_GPIO_WritePin(GPIOG, GPIO_PIN_8, GPIO_PIN_RESET)
#define LED_DRAG_RIGHT_SET            HAL_GPIO_WritePin(GPIOG, GPIO_PIN_7, GPIO_PIN_RESET)
#define LED_LOAD_SET                  HAL_GPIO_WritePin(GPIOG, GPIO_PIN_6, GPIO_PIN_RESET)
#define LED_ADJUST_SET                HAL_GPIO_WritePin(GPIOG, GPIO_PIN_5, GPIO_PIN_RESET)
#define LED_YAW_SET                   HAL_GPIO_WritePin(GPIOG, GPIO_PIN_4, GPIO_PIN_RESET)
#define LED_PITCH_SET                 HAL_GPIO_WritePin(GPIOG, GPIO_PIN_3, GPIO_PIN_RESET)
#define LED_YAW_ANGLE_ENCODER_SET     HAL_GPIO_WritePin(GPIOG, GPIO_PIN_2, GPIO_PIN_RESET)
#define LED_PITCH_ANGLE_ENCODER_SET   HAL_GPIO_WritePin(GPIOG, GPIO_PIN_1, GPIO_PIN_RESET)
#define LED_REMOTE_SET                HAL_GPIO_WritePin(GPIOF, GPIO_PIN_14, GPIO_PIN_RESET)
#define LED_PROBLEM_SET               HAL_GPIO_WritePin(GPIOE, GPIO_PIN_11, GPIO_PIN_RESET)

#define LED_DRAG_LEFT_RESET           HAL_GPIO_WritePin(GPIOG, GPIO_PIN_8, GPIO_PIN_SET)
#define LED_DRAG_RIGHT_RESET          HAL_GPIO_WritePin(GPIOG, GPIO_PIN_7, GPIO_PIN_SET)
#define LED_LOAD_RESET                HAL_GPIO_WritePin(GPIOG, GPIO_PIN_6, GPIO_PIN_SET)
#define LED_ADJUST_RESET              HAL_GPIO_WritePin(GPIOG, GPIO_PIN_5, GPIO_PIN_SET)
#define LED_YAW_RESET                 HAL_GPIO_WritePin(GPIOG, GPIO_PIN_4, GPIO_PIN_SET)
#define LED_PITCH_RESET               HAL_GPIO_WritePin(GPIOG, GPIO_PIN_3, GPIO_PIN_SET)
#define LED_YAW_ANGLE_ENCODER_RESET   HAL_GPIO_WritePin(GPIOG, GPIO_PIN_2, GPIO_PIN_SET)
#define LED_PITCH_ANGLE_ENCODER_RESET HAL_GPIO_WritePin(GPIOG, GPIO_PIN_1, GPIO_PIN_SET)
#define LED_REMOTE_RESET              HAL_GPIO_WritePin(GPIOF, GPIO_PIN_14, GPIO_PIN_SET)
#define LED_PROBLEM_RESET             HAL_GPIO_WritePin(GPIOE, GPIO_PIN_11, GPIO_PIN_SET)

extern void debug_light_thread(void const *argument);

#endif
