#ifndef HX711_H
#define HX711_H

#include "struct_typedef.h"

#define HX711_LEFT_SDA_PORT   GPIOC
#define HX711_LEFT_SCL_PORT   GPIOC
#define HX711_RIGHT_SDA_PORT  GPIOC
#define HX711_RIGHT_SCL_PORT  GPIOB

#define HX711_LEFT_SDA_PIN    GPIO_PIN_4
#define HX711_LEFT_SCL_PIN    GPIO_PIN_0
#define HX711_RIGHT_SDA_PIN   GPIO_PIN_2
#define HX711_RIGHT_SCL_PIN   GPIO_PIN_0

#define HX711_LEFT_SDA_READ   HAL_GPIO_ReadPin(HX711_LEFT_SDA_PORT, HX711_LEFT_SDA_PIN)
#define HX711_LEFT_SCL_SET    HAL_GPIO_WritePin(HX711_LEFT_SCL_PORT, HX711_LEFT_SCL_PIN, GPIO_PIN_SET)
#define HX711_LEFT_SCL_RESET  HAL_GPIO_WritePin(HX711_LEFT_SCL_PORT, HX711_LEFT_SCL_PIN, GPIO_PIN_RESET)
#define HX711_RIGHT_SDA_READ  HAL_GPIO_ReadPin(HX711_RIGHT_SDA_PORT, HX711_RIGHT_SDA_PIN)
#define HX711_RIGHT_SCL_SET   HAL_GPIO_WritePin(HX711_RIGHT_SCL_PORT, HX711_RIGHT_SCL_PIN, GPIO_PIN_SET)
#define HX711_RIGHT_SCL_RESET HAL_GPIO_WritePin(HX711_RIGHT_SCL_PORT, HX711_RIGHT_SCL_PIN, GPIO_PIN_RESET)

extern void hx711_read(void);
extern void get_hx711_data(fp32 *fl, fp32 *fr);

#endif